version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 18
    commands:
      - npm ci
      - echo "Node module installed"
  pre_build:
       - export CLOUDFRONT_ID="YOUR_CLOUDFRONT_DISTRIBUTION_ID"
  build:
    commands:
      - npm run build
      - echo "NPM build successful"
  post_build:
    commands:
      - aws s3 cp dist s3://deploybucketwildlife95 --recursive
      - echo "Build files copied to S3 successfully"
      - echo "CloudFront ID: $CLOUDFRONT_ID"
      - aws cloudfront create-invalidation --distribution-id $CLOUDFRONT_ID --paths "/*"

cache:
  paths:
    - 'node_modules/**/*'

artifacts:
  files:
    - '**/*'
  base-directory: 'dist'
